### PR TITLE
Fix bug with array size mismatch

### LINKED ISSUE #12: Fix bug with array size mismatch when db row count was less than batch size

### PR DESCRIPTION
**Pull request by OleksPal**

### CODE REVIEW

File: src/NBomber.LargeData/DataFeed.cs [hunk 1]
```diff
@@ -201,6 +224,12 @@ private T[] QueryItems(SqliteConnection connection, long startId, int count)
             itemsRead++;
         }
 
+        // Resize to actual items read
+        if (itemsRead < count)
```
Comment (AntyaDev) [inline src/NBomber.LargeData/DataFeed.cs]: remodel with Array pool

**Review by AntyaDev — CHANGES_REQUESTED** [review]

File: src/NBomber.LargeData/DataFeed.cs [hunk 2]
```diff
@@ -185,73 +166,83 @@ internal long LoadBatch(List<T> batch, long startId, int count)
...
         {
-            var missingCount = count - firstPart.Length;
-            var secondPart = QueryItems(connection, 1, missingCount);
-            batch.AddRange(secondPart);
-            return missingCount + 1;
-        }
+            // If dataset is smaller than requested count, load all items and repeat them
+            if (DataCount < count)
+            {
+                var itemsRead = QueryItems(connection, pooledArray, 1, (int)DataCount);
```
Comment (AntyaDev) [inline src/NBomber.LargeData/DataFeed.cs]: split this logic in 2 smaller methods. 1 for normal case and one for case when batch is > than db records

**Review by AntyaDev — CHANGES_REQUESTED** [review]
